### PR TITLE
Patch CMB2 - conflicts with other autoload scripts

### PR DESCRIPTION
**Pull request by fliespl**
https://github.com/CMB2/CMB2/issues/886
https://github.com/CMB2/CMB2/commit/5428430312d54390fe2370b316d2916362d35f8e

### CODE REVIEW

**Comment by EvanHerman** [comment]
@fliespl 

This shouldn't be conflicting with other autoloading scripts. The line:

```php
require_once 'bootstrap.php';
```

Found here https://github.com/EvanHerman/timeline-express/pull/42/files#diff-fcff4a11078a2e64cae3a0ccbabc7ef7L153

Is loading the bootstrap.php file using the relative path of the init file. It should only be loading the bootstrap.php file found in [/lib/admin/CMB2](https://github.com/EvanHerman/timeline-express/tree/master/lib/admin/CMB2).

Where are you running into a conflict? Can you provide an example of what other plugin you are using where the autoloader is conflicting with CMB2 inside of Timeline Express?

If this is a larger issue with CMB2, it may be wise to open up an issue/PR over on the [CMB2 github directory](https://github.com/CMB2/CMB2).

**Comment by fliespl** [comment]
Hi @EvanHerman,
I have described issue in CMB repository (links are in pull request) - https://github.com/CMB2/CMB2/issues/886

The issue is when set_include_path is used.

Also - patch was already integrated in CMB2 - https://github.com/CMB2/CMB2/commit/5428430312d54390fe2370b316d2916362d35f8e

**Comment by EvanHerman** [comment]
@fliespl This looks to be implemented on the `trunk` branch but hasn't been tagged as a release yet. I'm assuming this will be included in a `2.2.5/2.3` release? I can include the trunk branch files in the next release, but I'm not sure that it's stable enough.

**Comment by fliespl** [comment]
@EvanHerman it's okay to wait for final release :)

I just provided single line patch in case you would like to resolve it temporarily in your plugin before CMB2 update is out.

**Comment by EvanHerman** [comment]
I went back and took a second look at this and have decided that it would be best to remove CMB2 from our directory altogether, and set things up as a submodule. See https://github.com/EvanHerman/timeline-express/pull/45

This now includes the CMB2 fix you referenced above in our plugin, which should fix the problem moving forward.

Thanks again for bringing this to our attention!

**Comment by fliespl** [comment]
No worries - glad to be helpful!

**Pull request closed without merging**
