### PR TITLE
i18n: escape translation strings

### PR DESCRIPTION
**Pull request by ramiy**

### CODE REVIEW

**Comment by EvanHerman** [comment]
This issue should be resolved. If is not please reply here and I'll take a second look.

Thanks,
Evan

**Comment by ramiy** [comment]
@EvanHerman 

I see you haven't merged the changes.

Please check out the my changes here: d8c693871609177f0fef0c8936def34705bf67e8

You need to escape the translation strings for better security.

**Comment by EvanHerman** [comment]
Hey @ramiy,

I just went ahead and went back and updated all of the strings that I missed. Since the `master` branch and `development` branch were out of sync I had to go back and make the changes to the `development` branch so we can merge it back into `master` when 1.3.6 is ready for launch.

Feel free to review and make a pull request for any changes on the `development` branch.

5e45ac776fe5812d45b4bf7857bdedd8215ee680

Thanks again for reporting this!


Evan

**Comment by ramiy** [comment]
@EvanHerman 
If I want to contribute more code, which branch should I use?

**Comment by EvanHerman** [comment]
Hey @ramiy 

You can use the `development` branch (https://github.com/EvanHerman/timeline-express/tree/development) to make Pull requests on. I like to do my development there and then create a PR to merge the changes into `master`.

**Pull request closed without merging**
